### ISSUE TITLE
Allow a Pester Configuration File to be specified

### ISSUE THREAD

**Issue by Bummibaer** [pester/vscode-adapter#141]
I get an stacktrace on every Failure.
According to (https://pester.dev/docs/usage/output)
There is the Config variable  **StackTraceVerbosity :** 
Where can I set this?

**Comment by JustinGrote** [comment]
Because of the way we currently inject into Pester, we do not expose the ability to add your own custom options to invoke-pester because it may fail in weird ways. You can always try invoke-pester at the command line or add a PesterPreference to your session
https://pester.dev/docs/usage/configuration.

I'll leave this flagged as a possible future enhancement but it would require a lot of compatibility testing.
