### ISSUE TITLE
Errors in BeforeAll/AfterAll are not reflected in the UI

### ISSUE THREAD

**Issue by lujomu** [pester/vscode-adapter#90]
Consider the following test file:

    BeforeAll {
      Write-Error "Stop!!!" -ErrorAction 'Stop'
    }
    
    Context 'Context' {
      It '$True is $True' { $True | Should -BeExactly $True }
      It '$False is $False' { $False | Should -BeExactly $False }
    }

The UI (gutter icons, test explorer) looks like the tests were evaluated (the previous passed/failed states reappear), while only the 'Test Output' in the terminal indicates the error.

**Comment by JustinGrote** [comment]
@lujomu thanks for filing the issue. Hmm, this may be tricky due to how the test status is reported back from pester.

**Comment by ziesemer** [comment]
Failures from #85 also are contributing to this - which I'll be extending upon there shortly.

Is there any way to at least force a refresh / reload of the discovered tests and their statuses, shy of restarting VSC?  (I've not been able to find such an option so far...)  This may also be needed for other such failures I've been seeing - which I'm not yet sure are all related to these issues...

**Comment by JustinGrote** [comment]
@ziesemer I've decided not to add a timeout for now since tests can be long running, however I just added functionality so that new test runs will preempt existing test runs so that should help.

I've also added better error handling to the Powershell Runner which may be able to catch BeforeAll/AfterAll at certain levels. I'll try to add some tests for this.

**Comment by JustinGrote** [comment]
So in order to implement I need to implement these pester plugins: `'OneTimeTestTeardownEnd', 'EachBlockTeardownEnd', 'OneTimeBlockTeardownEnd', 'ContainerRunEnd'` and append a new result or error for the test if the failure doesn't occur in the test itself. This will probably take significant effort but I'll put it on the backlog.

**Comment by JustinGrote** [comment]
Looks like BeforeEach/AfterEach get reflected correctly, so it's just beforeall/afterall. That simplifies things, I have an idea for an approach

**Comment by JustinGrote** [comment]
Yeah I know, that's a bit more work to slve, I'm trying to apply my limited time to things I can fix within that time :)

**Comment by JustinGrote** [comment]
This is now dependent on an upstream bug being solved:
https://github.com/microsoft/vscode/issues/139224
